using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace InstallWalker.Core;

public static class ReportExporter
{
    /// <summary>Writes report.json, files.csv, registry.csv, changes.reg, silent-commands.txt and install.cmd.</summary>
    public static string Export(InstallMonitor m, AnalysisResult? preAnalysis, string folder)
    {
        Directory.CreateDirectory(folder);
        var candidates = m.Candidates.Concat(preAnalysis?.Candidates ?? new())
            .GroupBy(c => c.Kind + "|" + c.Command).Select(g => g.OrderByDescending(c => c.Confidence).First())
            .OrderBy(c => c.Kind).ThenByDescending(c => c.Confidence).ToList();

        var report = new
        {
            Tool = "InstallWalker",
            Installer = m.InstallerPath ?? preAnalysis?.Path,
            Technology = preAnalysis?.Technology,
            Evidence = preAnalysis?.Evidence,
            InstallerInfo = preAnalysis?.Info,
            m.Started, m.Stopped,
            PrimaryTempLocation = m.PrimaryTemp?.Path,
            TempLocations = m.TempLocations.OrderBy(t => t.FirstSeen),
            SilentCommands = candidates,
            PreservedPayloads = m.PreservedPayloads.Where(p => p.Value.Length > 0).ToDictionary(p => p.Key, p => p.Value),
            Processes = m.Processes?.Processes.OrderBy(p => p.Started),
            Files = m.Files.OrderBy(f => f.Path).Select(f => new { f.Path, f.NetResult, f.Area, f.Size, f.IsDirectory, f.FirstSeen, f.EventCount, f.RenamedFrom }),
            Registry = m.RegistryChanges,
        };
        var opts = new JsonSerializerOptions { WriteIndented = true, Converters = { new JsonStringEnumConverter() }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
        File.WriteAllText(Path.Combine(folder, "report.json"), JsonSerializer.Serialize(report, opts));

        var csv = new StringBuilder("Result,Area,Path,Size,IsDirectory,FirstSeen,Events,RenamedFrom\r\n");
        foreach (var f in m.Files.OrderBy(f => f.Path))
            csv.AppendJoin(',', Csv(f.NetResult), Csv(f.Area.ToString()), Csv(f.Path), f.Size?.ToString() ?? "", f.IsDirectory ? "1" : "0",
                f.FirstSeen.ToString("s"), f.EventCount, Csv(f.RenamedFrom ?? "")).Append("\r\n");
        File.WriteAllText(Path.Combine(folder, "files.csv"), csv.ToString(), Encoding.UTF8);

        var reg = new StringBuilder("Change,Key,Value,OldData,NewData\r\n");
        foreach (var r in m.RegistryChanges)
            reg.AppendJoin(',', Csv(r.Change), Csv(r.Key), Csv(r.ValueName ?? ""), Csv(r.OldData ?? ""), Csv(r.NewData ?? "")).Append("\r\n");
        File.WriteAllText(Path.Combine(folder, "registry.csv"), reg.ToString(), Encoding.UTF8);
        File.WriteAllText(Path.Combine(folder, "changes.reg"), RegistrySnapshot.ToRegFile(m.RegistryChanges), Encoding.Unicode);

        var txt = new StringBuilder();
        foreach (var g in candidates.GroupBy(c => c.Kind))
        {
            txt.AppendLine($"==== {g.Key} ====");
            foreach (var c in g)
                txt.AppendLine($"[{c.Confidence}] {c.Technology}  ({c.Source})").AppendLine("  " + c.Command)
                   .AppendLine(string.IsNullOrEmpty(c.Notes) ? "" : "  # " + c.Notes + Environment.NewLine);
        }
        File.WriteAllText(Path.Combine(folder, "silent-commands.txt"), txt.ToString());

        var best = candidates.FirstOrDefault(c => c.Kind == "Install" && !c.Command.StartsWith("("));
        var bestUn = candidates.FirstOrDefault(c => c.Kind == "Uninstall");
        if (best != null)
        {
            var cmd = new StringBuilder("@echo off\r\nrem Generated by InstallWalker - review before use\r\n")
                .Append($"rem Technology: {best.Technology} ({best.Confidence})\r\n")
                .Append("pushd \"%~dp0\"\r\n")
                .Append(best.Command.Replace(Path.GetDirectoryName(m.InstallerPath ?? preAnalysis?.Path ?? "") + "\\", "")).Append("\r\n")
                .Append("set RC=%ERRORLEVEL%\r\npopd\r\nrem 0 = success, 3010 = success (reboot required)\r\nexit /b %RC%\r\n");
            File.WriteAllText(Path.Combine(folder, "install.cmd"), cmd.ToString());
        }
        if (bestUn != null)
            File.WriteAllText(Path.Combine(folder, "uninstall.cmd"),
                $"@echo off\r\nrem Generated by InstallWalker - review before use\r\n{bestUn.Command}\r\nexit /b %ERRORLEVEL%\r\n");

        File.WriteAllLines(Path.Combine(folder, "session.log"), m.LogLines);
        return folder;
    }

    private static string Csv(string s) => s.IndexOfAny(new[] { ',', '"', '\n', '\r' }) >= 0 ? "\"" + s.Replace("\"", "\"\"") + "\"" : s;
}
